<?php

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * PHP Version 5.4.24
 * 
 * @author Ariane Krumel
 * 
**/

class RSSPlayer
{
  /**
  * property declarations
  */

  // method declarations

  /**
  * Private constructor so this utility class cannot be instantiated.
  */
  public function __construct(){
    /**
    * Main method.
    * 
    */

    /*
    * Input the source URL of an RSS 2.0 news feed.
    */
    $url = "http://www.rock1053.com/podcast/TheShow.xml";
    /*
    * Read XML input and initialize XMLTree. If input is not legal XML,
    * this statement will fail.
    */
    $xml = simplexml_load_file($url);

    /*
    * Check if XML is valid RSS 2.0 feed with correct structure
    */

    /*
    * Extract <channel> element.
    */
    $channel = $xml->channel;

    /*
    * Find all the item children of channel and process for output rows
    */

    /*foreach () {

    }*/

  }

  /**
  * Outputs the "opening" tags in the generated HTML file. These are the
  * expected elements generated by this method:
  * 
  * <html> <head> <title>the channel tag title as the page title</title>
  * </head> <body> <h1>the page title inside a link to the <channel> link<h1>
  * <p>
  * the channel description
  * </p>
  * <table>
  * <tr>
  * <th>Date</th>
  * <th>Subtitle</th>
  * <th>URL</th>
  * </tr>
  * 
  * @param $channel  the channel element XMLTree
  * 
  * @access private
  * @static
  * 
  */
  private static function outputHeader($channel) {

    /*
    * Output title if available
    */
    $titleIndex = $channel->title;
    echo "<html><head><title>" . $titleIndex . "</title>" . "</head><body><h1>";

    /*
    * Output link if available
    */
    $linkIndex = $channel->link;
    if ($linkIndex && $titleIndex) {
    echo "<a href='" . $linkIndex . "'>" . $titleIndex . "</a>";
    }
    echo "</h1>";

    /*
    * Output description if available
    */
    $linkIndex = $channel->description;
    if ($linkIndex) {
    echo "<p>" . $linkIndex . "</p>";
    }

    /*
    * Output starting tags for table
    */
    echo "<table border='1'><tr>";
    echo "<th>Date</th><th>Subtitle</th><th>URL</th>";
    echo "</tr>";

  }

  /**
  * Outputs the "closing" tags in the generated HTML file. These are the
  * expected elements generated by this method:
  * 
  * </table> </body> </html>
  * 
  * @access private
  * @static
  *
  */
  private static function outputFooter() {

    /*
    * Output remaining tag endings.
    */
    echo "</table></body></html>";

  }

}
